import { jsPDF } from "jspdf";
import { buildHealthReportMarkdown } from "./healthReport";
import { buildMedicationRecommendations } from "./medicationRecommendations";
import { loadLastTriage, loadPatientContextSnapshot } from "./triagePersistence";
import { SITE_NAME, SITE_TAGLINE, SITE_URL } from "./siteBranding";

const MARGIN = 14;
const PAGE_W = 210;
const LINE_H = 5.2;
const BODY_W = PAGE_W - MARGIN * 2;

function stripMarkdown(md: string): string {
  return md
    .replace(/^#+\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/^>\s+/gm, "")
    .replace(/`/g, "");
}

function drawHeader(doc: jsPDF) {
  doc.setFillColor(8, 18, 28);
  doc.rect(0, 0, PAGE_W, 32, "F");
  doc.setTextColor(0, 212, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(SITE_NAME, MARGIN, 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(180, 210, 220);
  doc.text(SITE_TAGLINE, MARGIN, 18);
  doc.text(SITE_URL, MARGIN, 23);
  doc.setFontSize(9);
  doc.text("Health & Triage Report (PDF)", MARGIN, 28);
}

function drawFooter(doc: jsPDF, pageNum: number, total: number) {
  const y = 287;
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y - 8, PAGE_W - MARGIN, y - 8);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(`${SITE_NAME} · ${SITE_URL}`, MARGIN, y - 3);
  doc.text(`Page ${pageNum} of ${total}`, PAGE_W - MARGIN, y - 3, { align: "right" });
  doc.text("Educational demo — not a medical record.", MARGIN, y + 2);
}

/** Download branded PDF health report with website name in header/footer. */
export async function downloadHealthReportPdf(): Promise<void> {
  const md = await buildHealthReportMarkdown();
  const triage = loadLastTriage();
  const patient = loadPatientContextSnapshot();
  const medRecs = buildMedicationRecommendations(triage, patient);

  let extra = "\n\nMedication guidance (educational — not a prescription)\n";
  if (medRecs.length === 0) {
    extra += "Complete triage first for medication suggestions.\n";
  } else {
    medRecs.forEach((r, i) => {
      extra += `${i + 1}. ${r.name} — ${r.purpose}. ${r.note}\n`;
    });
  }
  extra += `\nGenerated by ${SITE_NAME} (${SITE_URL})\n`;

  const plain = stripMarkdown(md + extra);
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  drawHeader(doc);

  const lines = doc.splitTextToSize(plain, BODY_W) as string[];
  let y = 38;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(25, 25, 25);

  for (const line of lines) {
    if (y > 272) {
      doc.addPage();
      doc.setFontSize(9);
      doc.setTextColor(0, 120, 140);
      doc.text(`${SITE_NAME} — continued`, MARGIN, 12);
      y = 20;
      doc.setFontSize(10);
      doc.setTextColor(25, 25, 25);
    }
    doc.text(line, MARGIN, y);
    y += LINE_H;
  }

  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawFooter(doc, p, total);
  }

  doc.save(`${SITE_NAME.replace(/\s+/g, "-").toLowerCase()}-health-report-${Date.now()}.pdf`);
}
